// GeoTrainer - base mundial
// Archivo generado para cargarse antes de script.js

const GEO_META = {
  "version": "1.0",
  "totalEntradas": 250,
  "estados": 195,
  "territorios": 52,
  "especiales": 3,
  "descripcion": "Base de datos de GeoTrainer: estados, territorios/dependencias/áreas ISO y entidades de estatus especial."
};

const GEO_DATA = [
  {
    "pais": "Afganistán",
    "capital": "Kabul",
    "continente": "Asia",
    "subregion": "Asia meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "AF",
    "lat": 33,
    "lon": 65,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Albania",
    "capital": "Tirana",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "AL",
    "lat": 41,
    "lon": 20,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Alemania",
    "capital": "Berlín",
    "continente": "Europa",
    "subregion": "Europa occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "DE",
    "lat": 51,
    "lon": 9,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Andorra",
    "capital": "Andorra la Vella",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "AD",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Angola",
    "capital": "Luanda",
    "continente": "África",
    "subregion": "África central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "AO",
    "lat": -12.5,
    "lon": 18.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Anguila",
    "capital": "The Valley",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "AI",
    "lat": 18.25,
    "lon": -63.16666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Antigua y Barbuda",
    "capital": "Saint John's",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "AG",
    "lat": 17.05,
    "lon": -61.8,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Antártida",
    "capital": null,
    "continente": "Antártida",
    "subregion": "Antártida",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": null,
    "iso2": "AQ",
    "lat": null,
    "lon": null,
    "quizCapital": false,
    "nota": "No tiene capital ni población permanente."
  },
  {
    "pais": "Arabia Saudí",
    "capital": "Riad",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SA",
    "lat": 25,
    "lon": 45,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Argelia",
    "capital": "Argel",
    "continente": "África",
    "subregion": "África septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "DZ",
    "lat": 28,
    "lon": 3,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Argentina",
    "capital": "Buenos Aires",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "AR",
    "lat": -34,
    "lon": -64,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Armenia",
    "capital": "Ereván",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "AM",
    "lat": 40,
    "lon": 45,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Aruba",
    "capital": "Oranjestad",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Países Bajos",
    "iso2": "AW",
    "lat": 12.5,
    "lon": -69.96666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Australia",
    "capital": "Canberra",
    "continente": "Oceanía",
    "subregion": "Australia y Nueva Zelanda",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "AU",
    "lat": -27,
    "lon": 133,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Austria",
    "capital": "Viena",
    "continente": "Europa",
    "subregion": "Europa occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "AT",
    "lat": 47.33333333,
    "lon": 13.33333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Azerbaiyán",
    "capital": "Bakú",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "AZ",
    "lat": 40.5,
    "lon": 47.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Bahamas",
    "capital": "Nassau",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BS",
    "lat": 24.25,
    "lon": -76,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Bangladés",
    "capital": "Dhaka",
    "continente": "Asia",
    "subregion": "Asia meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BD",
    "lat": 24,
    "lon": 90,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Barbados",
    "capital": "Bridgetown",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BB",
    "lat": 13.16666666,
    "lon": -59.53333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Baréin",
    "capital": "Manama",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BH",
    "lat": 26,
    "lon": 50.55,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Belice",
    "capital": "Belmopán",
    "continente": "América",
    "subregion": "Centroamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BZ",
    "lat": 17.25,
    "lon": -88.75,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Benín",
    "capital": "Porto-Novo",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BJ",
    "lat": 9.5,
    "lon": 2.25,
    "quizCapital": true,
    "nota": "Porto-Novo es la capital oficial; Cotonú alberga gran parte del Gobierno."
  },
  {
    "pais": "Bermudas",
    "capital": "Hamilton",
    "continente": "América",
    "subregion": "Norteamérica",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "BM",
    "lat": 32.33333333,
    "lon": -64.75,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Bielorrusia",
    "capital": "Minsk",
    "continente": "Europa",
    "subregion": "Europa oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BY",
    "lat": 53,
    "lon": 28,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Bolivia",
    "capital": "Sucre",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BO",
    "lat": -17,
    "lon": -65,
    "quizCapital": true,
    "nota": "Sucre es la capital constitucional; La Paz es la sede del Gobierno."
  },
  {
    "pais": "Bosnia y Herzegovina",
    "capital": "Sarajevo",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BA",
    "lat": 44,
    "lon": 18,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Botsuana",
    "capital": "Gaborone",
    "continente": "África",
    "subregion": "África austral",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BW",
    "lat": -22,
    "lon": 24,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Brasil",
    "capital": "Brasilia",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BR",
    "lat": -10,
    "lon": -55,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Brunéi",
    "capital": "Bandar Seri Begawan",
    "continente": "Asia",
    "subregion": "Sudeste asiático",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BN",
    "lat": 4.5,
    "lon": 114.66666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Bulgaria",
    "capital": "Sofía",
    "continente": "Europa",
    "subregion": "Europa oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BG",
    "lat": 43,
    "lon": 25,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Burkina Faso",
    "capital": "Ouagadougou",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BF",
    "lat": 13,
    "lon": -2,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Burundi",
    "capital": "Gitega",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BI",
    "lat": -3.5,
    "lon": 30,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Bután",
    "capital": "Thimphu",
    "continente": "Asia",
    "subregion": "Asia meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BT",
    "lat": 27.5,
    "lon": 90.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Bélgica",
    "capital": "Bruselas",
    "continente": "Europa",
    "subregion": "Europa occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "BE",
    "lat": 50.83333333,
    "lon": 4,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Cabo Verde",
    "capital": "Praia",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CV",
    "lat": 16,
    "lon": -24,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Camboya",
    "capital": "Nom Pen",
    "continente": "Asia",
    "subregion": "Sudeste asiático",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "KH",
    "lat": 13,
    "lon": 105,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Camerún",
    "capital": "Yaundé",
    "continente": "África",
    "subregion": "África central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CM",
    "lat": 6,
    "lon": 12,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Canadá",
    "capital": "Ottawa",
    "continente": "América",
    "subregion": "Norteamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CA",
    "lat": 60,
    "lon": -95,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Caribe neerlandés",
    "capital": null,
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Países Bajos",
    "iso2": "BQ",
    "lat": null,
    "lon": null,
    "quizCapital": false,
    "nota": "Bonaire, San Eustaquio y Saba forman una entidad ISO sin una única capital."
  },
  {
    "pais": "Catar",
    "capital": "Doha",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "QA",
    "lat": 25.5,
    "lon": 51.25,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Chad",
    "capital": "N'Djamena",
    "continente": "África",
    "subregion": "África central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TD",
    "lat": 15,
    "lon": 19,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Chequia",
    "capital": "Praga",
    "continente": "Europa",
    "subregion": "Europa oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CZ",
    "lat": 49.75,
    "lon": 15.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Chile",
    "capital": "Santiago",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CL",
    "lat": -30,
    "lon": -71,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "China",
    "capital": "Pekín",
    "continente": "Asia",
    "subregion": "Asia oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CN",
    "lat": 35,
    "lon": 105,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Chipre",
    "capital": "Nicosia",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CY",
    "lat": 35,
    "lon": 33,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Ciudad del Vaticano",
    "capital": "Ciudad del Vaticano",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Estado observador de la ONU",
    "parent": null,
    "iso2": "VA",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Colombia",
    "capital": "Bogotá",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CO",
    "lat": 4,
    "lon": -72,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Comoras",
    "capital": "Moroni",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "KM",
    "lat": -12.16666666,
    "lon": 44.25,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Corea del Norte",
    "capital": "Pionyang",
    "continente": "Asia",
    "subregion": "Asia oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "KP",
    "lat": 40,
    "lon": 127,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Corea del Sur",
    "capital": "Seúl",
    "continente": "Asia",
    "subregion": "Asia oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "KR",
    "lat": 37,
    "lon": 127.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Costa Rica",
    "capital": "San José",
    "continente": "América",
    "subregion": "Centroamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CR",
    "lat": 10,
    "lon": -84,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Costa de Marfil",
    "capital": "Yamusukro",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CI",
    "lat": 8,
    "lon": -5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Croacia",
    "capital": "Zagreb",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "HR",
    "lat": 45.16666666,
    "lon": 15.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Cuba",
    "capital": "La Habana",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CU",
    "lat": 21.5,
    "lon": -80,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Curazao",
    "capital": "Willemstad",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Países Bajos",
    "iso2": "CW",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Dinamarca",
    "capital": "Copenhague",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "DK",
    "lat": 56,
    "lon": 10,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Dominica",
    "capital": "Roseau",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "DM",
    "lat": 15.41666666,
    "lon": -61.33333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Ecuador",
    "capital": "Quito",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "EC",
    "lat": -2,
    "lon": -77.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Egipto",
    "capital": "El Cairo",
    "continente": "África",
    "subregion": "África septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "EG",
    "lat": 27,
    "lon": 30,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "El Salvador",
    "capital": "San Salvador",
    "continente": "América",
    "subregion": "Centroamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SV",
    "lat": 13.83333333,
    "lon": -88.91666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Emiratos Árabes Unidos",
    "capital": "Abu Dabi",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "AE",
    "lat": 24,
    "lon": 54,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Eritrea",
    "capital": "Asmara",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "ER",
    "lat": 15,
    "lon": 39,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Eslovaquia",
    "capital": "Bratislava",
    "continente": "Europa",
    "subregion": "Europa oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SK",
    "lat": 48.66666666,
    "lon": 19.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Eslovenia",
    "capital": "Liubliana",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SI",
    "lat": 46.11666666,
    "lon": 14.81666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "España",
    "capital": "Madrid",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "ES",
    "lat": 40,
    "lon": -4,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Estados Unidos",
    "capital": "Washington D. C.",
    "continente": "América",
    "subregion": "Norteamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "US",
    "lat": 38,
    "lon": -97,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Estonia",
    "capital": "Tallinn",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "EE",
    "lat": 59,
    "lon": 26,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Esuatini",
    "capital": "Lobamba",
    "continente": "África",
    "subregion": "África austral",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SZ",
    "lat": -26.5,
    "lon": 31.5,
    "quizCapital": true,
    "nota": "Mbabane es la capital administrativa; Lobamba es la capital real y legislativa."
  },
  {
    "pais": "Etiopía",
    "capital": "Adís Abeba",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "ET",
    "lat": 8,
    "lon": 38,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Filipinas",
    "capital": "Manila",
    "continente": "Asia",
    "subregion": "Sudeste asiático",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "PH",
    "lat": 13,
    "lon": 122,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Finlandia",
    "capital": "Helsinki",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "FI",
    "lat": 64,
    "lon": 26,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Fiyi",
    "capital": "Suva",
    "continente": "Oceanía",
    "subregion": "Melanesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "FJ",
    "lat": -18,
    "lon": 175,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Francia",
    "capital": "París",
    "continente": "Europa",
    "subregion": "Europa occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "FR",
    "lat": 46,
    "lon": 2,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Gabón",
    "capital": "Libreville",
    "continente": "África",
    "subregion": "África central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GA",
    "lat": -1,
    "lon": 11.75,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Gambia",
    "capital": "Banjul",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GM",
    "lat": 13.46666666,
    "lon": -16.56666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Georgia",
    "capital": "Tiflis",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GE",
    "lat": 42,
    "lon": 43.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Ghana",
    "capital": "Acra",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GH",
    "lat": 8,
    "lon": -2,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Gibraltar",
    "capital": "Gibraltar",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "GI",
    "lat": 36.13333333,
    "lon": -5.35,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Granada",
    "capital": "St. George's",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GD",
    "lat": 12.11666666,
    "lon": -61.66666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Grecia",
    "capital": "Atenas",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GR",
    "lat": 39,
    "lon": 22,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Groenlandia",
    "capital": "Nuuk",
    "continente": "América",
    "subregion": "Norteamérica",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Dinamarca",
    "iso2": "GL",
    "lat": 72,
    "lon": -40,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Guadalupe",
    "capital": "Basse-Terre",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "GP",
    "lat": 16.25,
    "lon": -61.583333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Guam",
    "capital": "Hagåtña",
    "continente": "Oceanía",
    "subregion": "Micronesia",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Estados Unidos",
    "iso2": "GU",
    "lat": 13.46666666,
    "lon": 144.78333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Guatemala",
    "capital": "Ciudad de Guatemala",
    "continente": "América",
    "subregion": "Centroamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GT",
    "lat": 15.5,
    "lon": -90.25,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Guayana Francesa",
    "capital": "Cayena",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "GF",
    "lat": 4,
    "lon": -53,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Guernesey",
    "capital": "Saint Peter Port",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Dependencia de la Corona británica",
    "iso2": "GG",
    "lat": 49.46666666,
    "lon": -2.58333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Guinea",
    "capital": "Conakry",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GN",
    "lat": 11,
    "lon": -10,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Guinea Ecuatorial",
    "capital": "Malabo",
    "continente": "África",
    "subregion": "África central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GQ",
    "lat": 2,
    "lon": 10,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Guinea-Bisáu",
    "capital": "Bissau",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GW",
    "lat": 12,
    "lon": -15,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Guyana",
    "capital": "Georgetown",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GY",
    "lat": 5,
    "lon": -59,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Haití",
    "capital": "Puerto Príncipe",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "HT",
    "lat": 19,
    "lon": -72.41666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Honduras",
    "capital": "Tegucigalpa",
    "continente": "América",
    "subregion": "Centroamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "HN",
    "lat": 15,
    "lon": -86.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Hungría",
    "capital": "Budapest",
    "continente": "Europa",
    "subregion": "Europa oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "HU",
    "lat": 47,
    "lon": 20,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "India",
    "capital": "Nueva Delhi",
    "continente": "Asia",
    "subregion": "Asia meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "IN",
    "lat": 20,
    "lon": 77,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Indonesia",
    "capital": "Yakarta",
    "continente": "Asia",
    "subregion": "Sudeste asiático",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "ID",
    "lat": -5,
    "lon": 120,
    "quizCapital": true,
    "nota": "Yakarta sigue siendo la capital efectiva hasta que se formalice por decreto presidencial el traslado a Nusantara."
  },
  {
    "pais": "Irak",
    "capital": "Bagdad",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "IQ",
    "lat": 33,
    "lon": 44,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Irlanda",
    "capital": "Dublín",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "IE",
    "lat": 53,
    "lon": -8,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Irán",
    "capital": "Teherán",
    "continente": "Asia",
    "subregion": "Asia meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "IR",
    "lat": 32,
    "lon": 53,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Isla Bouvet",
    "capital": null,
    "continente": "Antártida",
    "subregion": "Atlántico sur",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Noruega",
    "iso2": "BV",
    "lat": null,
    "lon": null,
    "quizCapital": false,
    "nota": "Territorio deshabitado, sin capital."
  },
  {
    "pais": "Isla Norfolk",
    "capital": "Kingston",
    "continente": "Oceanía",
    "subregion": "Australia y Nueva Zelanda",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Australia",
    "iso2": "NF",
    "lat": -29.03333333,
    "lon": 167.95,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Isla de Man",
    "capital": "Douglas",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Dependencia de la Corona británica",
    "iso2": "IM",
    "lat": 54.25,
    "lon": -4.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Isla de Navidad",
    "capital": "Flying Fish Cove",
    "continente": "Oceanía",
    "subregion": "Australia y Nueva Zelanda",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Australia",
    "iso2": "CX",
    "lat": -10.5,
    "lon": 105.66666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islandia",
    "capital": "Reikiavik",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "IS",
    "lat": 65,
    "lon": -18,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Aland",
    "capital": "Mariehamn",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Finlandia",
    "iso2": "AX",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Caimán",
    "capital": "George Town",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "KY",
    "lat": 19.5,
    "lon": -80.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Cocos",
    "capital": "West Island",
    "continente": "Oceanía",
    "subregion": "Australia y Nueva Zelanda",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Australia",
    "iso2": "CC",
    "lat": -12.5,
    "lon": 96.83333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Cook",
    "capital": "Avarua",
    "continente": "Oceanía",
    "subregion": "Polinesia",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Nueva Zelanda",
    "iso2": "CK",
    "lat": -21.23333333,
    "lon": -159.76666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Feroe",
    "capital": "Tórshavn",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Dinamarca",
    "iso2": "FO",
    "lat": 62,
    "lon": -7,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Georgia del Sur y Sandwich del Sur",
    "capital": "King Edward Point",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "GS",
    "lat": -54.5,
    "lon": -37,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Heard y McDonald",
    "capital": null,
    "continente": "Antártida",
    "subregion": "Océano Índico austral",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Australia",
    "iso2": "HM",
    "lat": -53.1,
    "lon": 72.51666666,
    "quizCapital": false,
    "nota": "Territorio deshabitado, sin capital."
  },
  {
    "pais": "Islas Malvinas",
    "capital": "Stanley",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "FK",
    "lat": -51.75,
    "lon": -59,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Marianas del Norte",
    "capital": "Saipán",
    "continente": "Oceanía",
    "subregion": "Micronesia",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Estados Unidos",
    "iso2": "MP",
    "lat": 15.2,
    "lon": 145.75,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Marshall",
    "capital": "Majuro",
    "continente": "Oceanía",
    "subregion": "Micronesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MH",
    "lat": 9,
    "lon": 168,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Pitcairn",
    "capital": "Adamstown",
    "continente": "Oceanía",
    "subregion": "Polinesia",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "PN",
    "lat": -25.06666666,
    "lon": -130.1,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Salomón",
    "capital": "Honiara",
    "continente": "Oceanía",
    "subregion": "Melanesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SB",
    "lat": -8,
    "lon": 159,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Turcas y Caicos",
    "capital": "Cockburn Town",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "TC",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Vírgenes Británicas",
    "capital": "Road Town",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "VG",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas Vírgenes de EE. UU.",
    "capital": "Charlotte Amalie",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Estados Unidos",
    "iso2": "VI",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Islas menores alejadas de EE. UU.",
    "capital": null,
    "continente": "Oceanía",
    "subregion": "Micronesia",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Estados Unidos",
    "iso2": "UM",
    "lat": null,
    "lon": null,
    "quizCapital": false,
    "nota": "Conjunto de islas menores sin capital única."
  },
  {
    "pais": "Israel",
    "capital": "Jerusalem",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "IL",
    "lat": 31.5,
    "lon": 34.75,
    "quizCapital": true,
    "nota": "Jerusalén es la capital declarada por Israel; su estatus internacional es objeto de disputa."
  },
  {
    "pais": "Italia",
    "capital": "Roma",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "IT",
    "lat": 42.83333333,
    "lon": 12.83333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Jamaica",
    "capital": "Kingston",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "JM",
    "lat": 18.25,
    "lon": -77.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Japón",
    "capital": "Tokio",
    "continente": "Asia",
    "subregion": "Asia oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "JP",
    "lat": 36,
    "lon": 138,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Jersey",
    "capital": "Saint Helier",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Dependencia de la Corona británica",
    "iso2": "JE",
    "lat": 49.25,
    "lon": -2.16666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Jordania",
    "capital": "Amán",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "JO",
    "lat": 31,
    "lon": 36,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Kazajistán",
    "capital": "Astaná",
    "continente": "Asia",
    "subregion": "Asia central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "KZ",
    "lat": 48,
    "lon": 68,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Kenia",
    "capital": "Nairobi",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "KE",
    "lat": 1,
    "lon": 38,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Kirguistán",
    "capital": "Biskek",
    "continente": "Asia",
    "subregion": "Asia central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "KG",
    "lat": 41,
    "lon": 75,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Kiribati",
    "capital": "Tarawa del Sur",
    "continente": "Oceanía",
    "subregion": "Micronesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "KI",
    "lat": 1.41666666,
    "lon": 173,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Kosovo",
    "capital": "Pristina",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "especial",
    "estatus": "Reconocimiento internacional parcial",
    "parent": null,
    "iso2": "XK",
    "lat": 42.6026,
    "lon": 20.903,
    "quizCapital": true,
    "nota": "Kosovo tiene reconocimiento internacional parcial y no es miembro de la ONU."
  },
  {
    "pais": "Kuwait",
    "capital": "Kuwait",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "KW",
    "lat": 29.5,
    "lon": 45.75,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Laos",
    "capital": "Vientián",
    "continente": "Asia",
    "subregion": "Sudeste asiático",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "LA",
    "lat": 18,
    "lon": 105,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Lesoto",
    "capital": "Maseru",
    "continente": "África",
    "subregion": "África austral",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "LS",
    "lat": -29.5,
    "lon": 28.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Letonia",
    "capital": "Riga",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "LV",
    "lat": 57,
    "lon": 25,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Liberia",
    "capital": "Monrovia",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "LR",
    "lat": 6.5,
    "lon": -9.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Libia",
    "capital": "Trípoli",
    "continente": "África",
    "subregion": "África septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "LY",
    "lat": 25,
    "lon": 17,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Liechtenstein",
    "capital": "Vaduz",
    "continente": "Europa",
    "subregion": "Europa occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "LI",
    "lat": 47.26666666,
    "lon": 9.53333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Lituania",
    "capital": "Vilnius",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "LT",
    "lat": 56,
    "lon": 24,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Luxemburgo",
    "capital": "Luxembourg",
    "continente": "Europa",
    "subregion": "Europa occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "LU",
    "lat": 49.75,
    "lon": 6.16666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Líbano",
    "capital": "Beirut",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "LB",
    "lat": 33.83333333,
    "lon": 35.83333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Macedonia del Norte",
    "capital": "Skopie",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MK",
    "lat": 41.83333333,
    "lon": 22,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Madagascar",
    "capital": "Antananarivo",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MG",
    "lat": -20,
    "lon": 47,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Malasia",
    "capital": "Kuala Lumpur",
    "continente": "Asia",
    "subregion": "Sudeste asiático",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MY",
    "lat": 2.5,
    "lon": 112.5,
    "quizCapital": true,
    "nota": "Kuala Lumpur es la capital; Putrajaya alberga gran parte de la administración federal."
  },
  {
    "pais": "Malaui",
    "capital": "Lilongwe",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MW",
    "lat": -13.5,
    "lon": 34,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Maldivas",
    "capital": "Malé",
    "continente": "Asia",
    "subregion": "Asia meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MV",
    "lat": 3.25,
    "lon": 73,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Mali",
    "capital": "Bamako",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "ML",
    "lat": 17,
    "lon": -4,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Malta",
    "capital": "Valletta",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MT",
    "lat": 35.83333333,
    "lon": 14.58333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Marruecos",
    "capital": "Rabat",
    "continente": "África",
    "subregion": "África septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MA",
    "lat": 32,
    "lon": -5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Martinica",
    "capital": "Fort-de-France",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "MQ",
    "lat": 14.666667,
    "lon": -61,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Mauricio",
    "capital": "Port Louis",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MU",
    "lat": -20.28333333,
    "lon": 57.55,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Mauritania",
    "capital": "Nouakchott",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MR",
    "lat": 20,
    "lon": -12,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Mayotte",
    "capital": "Mamoudzou",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "YT",
    "lat": -12.83333333,
    "lon": 45.16666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Micronesia",
    "capital": "Palikir",
    "continente": "Oceanía",
    "subregion": "Micronesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "FM",
    "lat": 6.91666666,
    "lon": 158.25,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Moldavia",
    "capital": "Chișinău",
    "continente": "Europa",
    "subregion": "Europa oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MD",
    "lat": 47,
    "lon": 29,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Mongolia",
    "capital": "Ulán Bator",
    "continente": "Asia",
    "subregion": "Asia oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MN",
    "lat": 46,
    "lon": 105,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Montenegro",
    "capital": "Podgorica",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "ME",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Montserrat",
    "capital": "Plymouth",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "MS",
    "lat": 16.75,
    "lon": -62.2,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Mozambique",
    "capital": "Maputo",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MZ",
    "lat": -18.25,
    "lon": 35,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Myanmar (Birmania)",
    "capital": "Naipyidó",
    "continente": "Asia",
    "subregion": "Sudeste asiático",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MM",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "México",
    "capital": "Ciudad de México",
    "continente": "América",
    "subregion": "Centroamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MX",
    "lat": 23,
    "lon": -102,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Mónaco",
    "capital": "Monaco",
    "continente": "Europa",
    "subregion": "Europa occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "MC",
    "lat": 43.73333333,
    "lon": 7.4,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Namibia",
    "capital": "Windhoek",
    "continente": "África",
    "subregion": "África austral",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "NA",
    "lat": -22,
    "lon": 17,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Nauru",
    "capital": "Yaren",
    "continente": "Oceanía",
    "subregion": "Micronesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "NR",
    "lat": -0.53333333,
    "lon": 166.91666666,
    "quizCapital": true,
    "nota": "Nauru no tiene una capital oficial; Yaren se usa habitualmente como capital de facto."
  },
  {
    "pais": "Nepal",
    "capital": "Katmandú",
    "continente": "Asia",
    "subregion": "Asia meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "NP",
    "lat": 28,
    "lon": 84,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Nicaragua",
    "capital": "Managua",
    "continente": "América",
    "subregion": "Centroamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "NI",
    "lat": 13,
    "lon": -85,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Nigeria",
    "capital": "Abuya",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "NG",
    "lat": 10,
    "lon": 8,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Niue",
    "capital": "Alofi",
    "continente": "Oceanía",
    "subregion": "Polinesia",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Nueva Zelanda",
    "iso2": "NU",
    "lat": -19.03333333,
    "lon": -169.86666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Noruega",
    "capital": "Oslo",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "NO",
    "lat": 62,
    "lon": 10,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Nueva Caledonia",
    "capital": "Numea",
    "continente": "Oceanía",
    "subregion": "Melanesia",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "NC",
    "lat": -21.5,
    "lon": 165.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Nueva Zelanda",
    "capital": "Wellington",
    "continente": "Oceanía",
    "subregion": "Australia y Nueva Zelanda",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "NZ",
    "lat": -41,
    "lon": 174,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Níger",
    "capital": "Niamey",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "NE",
    "lat": 16,
    "lon": 8,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Omán",
    "capital": "Mascate",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "OM",
    "lat": 21,
    "lon": 57,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Pakistán",
    "capital": "Islamabad",
    "continente": "Asia",
    "subregion": "Asia meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "PK",
    "lat": 30,
    "lon": 70,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Palaos",
    "capital": "Ngerulmud",
    "continente": "Oceanía",
    "subregion": "Micronesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "PW",
    "lat": 7.5,
    "lon": 134.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Palestina",
    "capital": "Ramala",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Estado observador de la ONU",
    "parent": null,
    "iso2": "PS",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": "Ramala funciona como sede administrativa. El Estado de Palestina reclama Jerusalén Este como capital."
  },
  {
    "pais": "Panamá",
    "capital": "Ciudad de Panamá",
    "continente": "América",
    "subregion": "Centroamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "PA",
    "lat": 9,
    "lon": -80,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Papúa Nueva Guinea",
    "capital": "Puerto Moresby",
    "continente": "Oceanía",
    "subregion": "Melanesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "PG",
    "lat": -6,
    "lon": 147,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Paraguay",
    "capital": "Asunción",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "PY",
    "lat": -23,
    "lon": -58,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Países Bajos",
    "capital": "Ámsterdam",
    "continente": "Europa",
    "subregion": "Europa occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "NL",
    "lat": 52.5,
    "lon": 5.75,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Perú",
    "capital": "Lima",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "PE",
    "lat": -10,
    "lon": -76,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Polinesia Francesa",
    "capital": "Papeete",
    "continente": "Oceanía",
    "subregion": "Polinesia",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "PF",
    "lat": -15,
    "lon": -140,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Polonia",
    "capital": "Varsovia",
    "continente": "Europa",
    "subregion": "Europa oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "PL",
    "lat": 52,
    "lon": 20,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Portugal",
    "capital": "Lisboa",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "PT",
    "lat": 39.5,
    "lon": -8,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Puerto Rico",
    "capital": "San Juan",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Estados Unidos",
    "iso2": "PR",
    "lat": 18.25,
    "lon": -66.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "RAE de Hong Kong (China)",
    "capital": "Hong Kong",
    "continente": "Asia",
    "subregion": "Asia oriental",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "China",
    "iso2": "HK",
    "lat": 22.25,
    "lon": 114.16666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "RAE de Macao (China)",
    "capital": "Macao",
    "continente": "Asia",
    "subregion": "Asia oriental",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "China",
    "iso2": "MO",
    "lat": 22.16666666,
    "lon": 113.55,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Reino Unido",
    "capital": "Londres",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "GB",
    "lat": 54,
    "lon": -2,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "República Centroafricana",
    "capital": "Bangui",
    "continente": "África",
    "subregion": "África central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CF",
    "lat": 7,
    "lon": 21,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "República Democrática del Congo",
    "capital": "Kinsasa",
    "continente": "África",
    "subregion": "África central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CD",
    "lat": 0,
    "lon": 25,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "República Dominicana",
    "capital": "Santo Domingo",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "DO",
    "lat": 19,
    "lon": -70.66666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "República del Congo",
    "capital": "Brazzaville",
    "continente": "África",
    "subregion": "África central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CG",
    "lat": -1,
    "lon": 15,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Reunión",
    "capital": "Saint-Denis",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "RE",
    "lat": -21.15,
    "lon": 55.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Ruanda",
    "capital": "Kigali",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "RW",
    "lat": -2,
    "lon": 30,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Rumanía",
    "capital": "Bucarest",
    "continente": "Europa",
    "subregion": "Europa oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "RO",
    "lat": 46,
    "lon": 25,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Rusia",
    "capital": "Moscú",
    "continente": "Europa",
    "subregion": "Europa oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "RU",
    "lat": 60,
    "lon": 100,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Samoa",
    "capital": "Apia",
    "continente": "Oceanía",
    "subregion": "Polinesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "WS",
    "lat": -13.58333333,
    "lon": -172.33333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Samoa Americana",
    "capital": "Pago Pago",
    "continente": "Oceanía",
    "subregion": "Polinesia",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Estados Unidos",
    "iso2": "AS",
    "lat": -14.33333333,
    "lon": -170,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "San Bartolomé",
    "capital": "Gustavia",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "BL",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "San Cristóbal y Nieves",
    "capital": "Basseterre",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "KN",
    "lat": 17.33333333,
    "lon": -62.75,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "San Marino",
    "capital": "City of San Marino",
    "continente": "Europa",
    "subregion": "Europa meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SM",
    "lat": 43.76666666,
    "lon": 12.41666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "San Martín",
    "capital": "Marigot",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "MF",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "San Pedro y Miquelón",
    "capital": "Saint-Pierre",
    "continente": "América",
    "subregion": "Norteamérica",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "PM",
    "lat": 46.83333333,
    "lon": -56.33333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "San Vicente y las Granadinas",
    "capital": "Kingstown",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "VC",
    "lat": 13.25,
    "lon": -61.2,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Santa Elena",
    "capital": "Jamestown",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "SH",
    "lat": -15.95,
    "lon": -5.7,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Santa Lucía",
    "capital": "Castries",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "LC",
    "lat": 13.88333333,
    "lon": -60.96666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Santo Tomé y Príncipe",
    "capital": "São Tomé",
    "continente": "África",
    "subregion": "África central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "ST",
    "lat": 1,
    "lon": 7,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Senegal",
    "capital": "Dakar",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SN",
    "lat": 14,
    "lon": -14,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Serbia",
    "capital": "Belgrado",
    "continente": "Europa",
    "subregion": "Europa oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "RS",
    "lat": 44.1305021,
    "lon": 16.4284181,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Seychelles",
    "capital": "Victoria",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SC",
    "lat": -4.58333333,
    "lon": 55.66666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Sierra Leona",
    "capital": "Freetown",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SL",
    "lat": 8.5,
    "lon": -11.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Singapur",
    "capital": "Singapur",
    "continente": "Asia",
    "subregion": "Sudeste asiático",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SG",
    "lat": 1.36666666,
    "lon": 103.8,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Sint Maarten",
    "capital": "Philipsburg",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Países Bajos",
    "iso2": "SX",
    "lat": null,
    "lon": null,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Siria",
    "capital": "Damasco",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SY",
    "lat": 35,
    "lon": 38,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Somalia",
    "capital": "Mogadishu",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SO",
    "lat": 10,
    "lon": 49,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Sri Lanka",
    "capital": "Colombo",
    "continente": "Asia",
    "subregion": "Asia meridional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "LK",
    "lat": 7,
    "lon": 81,
    "quizCapital": true,
    "nota": "Sri Jayawardenepura Kotte es la capital legislativa; Colombo es el principal centro ejecutivo y económico."
  },
  {
    "pais": "Sudáfrica",
    "capital": "Pretoria",
    "continente": "África",
    "subregion": "África austral",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "ZA",
    "lat": -29,
    "lon": 24,
    "quizCapital": true,
    "nota": "Sudáfrica tiene tres capitales: Pretoria (ejecutiva), Ciudad del Cabo (legislativa) y Bloemfontein (judicial)."
  },
  {
    "pais": "Sudán",
    "capital": "Khartoum",
    "continente": "África",
    "subregion": "África septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SD",
    "lat": 15,
    "lon": 30,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Sudán del Sur",
    "capital": "Juba",
    "continente": "África",
    "subregion": "África central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SS",
    "lat": 7,
    "lon": 30,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Suecia",
    "capital": "Estocolmo",
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SE",
    "lat": 62,
    "lon": 15,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Suiza",
    "capital": "Berna",
    "continente": "Europa",
    "subregion": "Europa occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "CH",
    "lat": 47,
    "lon": 8,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Surinam",
    "capital": "Paramaribo",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "SR",
    "lat": 4,
    "lon": -56,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Svalbard y Jan Mayen",
    "capital": null,
    "continente": "Europa",
    "subregion": "Europa septentrional",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Noruega",
    "iso2": "SJ",
    "lat": 78,
    "lon": 20,
    "quizCapital": false,
    "nota": "Svalbard y Jan Mayen forman una entidad ISO sin una única capital."
  },
  {
    "pais": "Sáhara Occidental",
    "capital": null,
    "continente": "África",
    "subregion": "África septentrional",
    "categoria": "especial",
    "estatus": "Entidad geopolítica de estatus especial",
    "parent": null,
    "iso2": "EH",
    "lat": 24.5,
    "lon": -13,
    "quizCapital": false,
    "nota": "Territorio de estatus disputado; se excluye del modo capitales por defecto."
  },
  {
    "pais": "Tailandia",
    "capital": "Bangkok",
    "continente": "Asia",
    "subregion": "Sudeste asiático",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TH",
    "lat": 15,
    "lon": 100,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Taiwán",
    "capital": "Taipéi",
    "continente": "Asia",
    "subregion": "Asia oriental",
    "categoria": "especial",
    "estatus": "Entidad geopolítica de estatus especial",
    "parent": null,
    "iso2": "TW",
    "lat": 23.5,
    "lon": 121,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Tanzania",
    "capital": "Dodoma",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TZ",
    "lat": -6,
    "lon": 35,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Tayikistán",
    "capital": "Dusambé",
    "continente": "Asia",
    "subregion": "Asia central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TJ",
    "lat": 39,
    "lon": 71,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Territorio Británico del Océano Índico",
    "capital": "Diego García",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Reino Unido",
    "iso2": "IO",
    "lat": -6,
    "lon": 71.5,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Territorios Australes Franceses",
    "capital": null,
    "continente": "Antártida",
    "subregion": "Océano Índico austral",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "TF",
    "lat": -49.25,
    "lon": 69.167,
    "quizCapital": false,
    "nota": "Territorios dispersos sin una capital local única."
  },
  {
    "pais": "Timor Oriental",
    "capital": "Dili",
    "continente": "Asia",
    "subregion": "Sudeste asiático",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TL",
    "lat": -8.83333333,
    "lon": 125.91666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Togo",
    "capital": "Lomé",
    "continente": "África",
    "subregion": "África occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TG",
    "lat": 8,
    "lon": 1.16666666,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Tokelau",
    "capital": null,
    "continente": "Oceanía",
    "subregion": "Polinesia",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Nueva Zelanda",
    "iso2": "TK",
    "lat": -9,
    "lon": -172,
    "quizCapital": false,
    "nota": "Tokelau no tiene una capital única."
  },
  {
    "pais": "Tonga",
    "capital": "Nukualofa",
    "continente": "Oceanía",
    "subregion": "Polinesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TO",
    "lat": -20,
    "lon": -175,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Trinidad y Tobago",
    "capital": "Port of Spain",
    "continente": "América",
    "subregion": "Caribe",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TT",
    "lat": 11,
    "lon": -61,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Turkmenistán",
    "capital": "Asjabad",
    "continente": "Asia",
    "subregion": "Asia central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TM",
    "lat": 40,
    "lon": 60,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Turquía",
    "capital": "Ankara",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TR",
    "lat": 39,
    "lon": 35,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Tuvalu",
    "capital": "Funafuti",
    "continente": "Oceanía",
    "subregion": "Polinesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TV",
    "lat": -8,
    "lon": 178,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Túnez",
    "capital": "Túnez",
    "continente": "África",
    "subregion": "África septentrional",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "TN",
    "lat": 34,
    "lon": 9,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Ucrania",
    "capital": "Kyiv",
    "continente": "Europa",
    "subregion": "Europa oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "UA",
    "lat": 49,
    "lon": 32,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Uganda",
    "capital": "Kampala",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "UG",
    "lat": 1,
    "lon": 32,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Uruguay",
    "capital": "Montevideo",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "UY",
    "lat": -33,
    "lon": -56,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Uzbekistán",
    "capital": "Taskent",
    "continente": "Asia",
    "subregion": "Asia central",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "UZ",
    "lat": 41,
    "lon": 64,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Vanuatu",
    "capital": "Port Vila",
    "continente": "Oceanía",
    "subregion": "Melanesia",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "VU",
    "lat": -16,
    "lon": 167,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Venezuela",
    "capital": "Caracas",
    "continente": "América",
    "subregion": "Sudamérica",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "VE",
    "lat": 8,
    "lon": -66,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Vietnam",
    "capital": "Hanói",
    "continente": "Asia",
    "subregion": "Sudeste asiático",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "VN",
    "lat": 16.16666666,
    "lon": 107.83333333,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Wallis y Futuna",
    "capital": "Mata-Utu",
    "continente": "Oceanía",
    "subregion": "Polinesia",
    "categoria": "territorio",
    "estatus": "Territorio, dependencia o área especial",
    "parent": "Francia",
    "iso2": "WF",
    "lat": -13.3,
    "lon": -176.2,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Yemen",
    "capital": "Saná",
    "continente": "Asia",
    "subregion": "Asia occidental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "YE",
    "lat": 15,
    "lon": 48,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Yibuti",
    "capital": "Djibouti",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "DJ",
    "lat": 11.5,
    "lon": 43,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Zambia",
    "capital": "Lusaka",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "ZM",
    "lat": -15,
    "lon": 30,
    "quizCapital": true,
    "nota": null
  },
  {
    "pais": "Zimbabue",
    "capital": "Harare",
    "continente": "África",
    "subregion": "África oriental",
    "categoria": "estado",
    "estatus": "Miembro de la ONU",
    "parent": null,
    "iso2": "ZW",
    "lat": -20,
    "lon": 30,
    "quizCapital": true,
    "nota": null
  }
];
